use std::collections::HashMap;
use once_cell::sync::Lazy;

pub static ITEMS: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| {
    let mut m = HashMap::new();
    m.insert("amrc", "i_Amulet of Recall");
    m.insert("ankh", "i_Ankh of Reincarnation");
    m.insert("belv", "i_Boots of Quel'Thalas +6");
    m.insert("bgst", "i_Belt of Giant Strength +6");
    m.insert("bspd", "i_Boots of Speed");
    m.insert("ccmd", "i_Scepter of Mastery");
    m.insert("ciri", "i_Robe of the Magi +6");
    m.insert("ckng", "i_Crown of Kings +5");
    m.insert("clsd", "i_Cloak of Shadows");
    m.insert("crys", "i_Crystal Ball");
    m.insert("desc", "i_Kelen's Dagger of Escape");
    m.insert("gemt", "i_Gem of True Seeing");
    m.insert("gobm", "i_Goblin Land Mines");
    m.insert("gsou", "i_Soul Gem");
    m.insert("guvi", "i_Glyph of Ultravision");
    m.insert("gfor", "i_Glyph of Fortification");
    m.insert("soul", "i_Soul");
    m.insert("mdpb", "i_Medusa Pebble");
    m.insert("rag1", "i_Slippers of Agility +3");
    m.insert("rat3", "i_Claws of Attack +3");
    m.insert("rin1", "i_Mantle of Intelligence +3");
    m.insert("rde1", "i_Ring of Protection +2");
    m.insert("rde2", "i_Ring of Protection +3");
    m.insert("rde3", "i_Ring of Protection +4");
    m.insert("rhth", "i_Khadgar's Gem of Health");
    m.insert("rst1", "i_Gauntlets of Ogre Strength +3");
    m.insert("ofir", "i_Orb of Fire");
    m.insert("ofro", "i_Orb of Frost");
    m.insert("olig", "i_Orb of Lightning");
    m.insert("oli2", "i_Orb of Lightning");
    m.insert("oven", "i_Orb of Venom");
    m.insert("odef", "i_Orb of Darkness");
    m.insert("ocor", "i_Orb of Corruption");
    m.insert("pdiv", "i_Potion of Divinity");
    m.insert("phea", "i_Potion of Healing");
    m.insert("pghe", "i_Potion of Greater Healing");
    m.insert("pinv", "i_Potion of Invisibility");
    m.insert("pgin", "i_Potion of Greater Invisibility");
    m.insert("pman", "i_Potion of Mana");
    m.insert("pgma", "i_Potion of Greater Mana");
    m.insert("pnvu", "i_Potion of Invulnerability");
    m.insert("pnvl", "i_Potion of Lesser Invulnerability");
    m.insert("pres", "i_Potion of Restoration");
    m.insert("pspd", "i_Potion of Speed");
    m.insert("rlif", "i_Ring of Regeneration");
    m.insert("rwiz", "i_Sobi Mask");
    m.insert("sfog", "i_Horn of the Clouds");
    m.insert("shea", "i_Scroll of Healing");
    m.insert("sman", "i_Scroll of Mana");
    m.insert("spro", "i_Scroll of Protection");
    m.insert("sres", "i_Scroll of Restoration");
    m.insert("ssil", "i_Staff of Silence");
    m.insert("stwp", "i_Scroll of Town Portal");
    m.insert("tels", "i_Goblin Night Scope");
    m.insert("tdex", "i_Tome of Agility");
    m.insert("texp", "i_Tome of Experience");
    m.insert("tint", "i_Tome of Intelligence");
    m.insert("tkno", "i_Tome of Power");
    m.insert("tstr", "i_Tome of Strength");
    m.insert("ward", "i_Warsong Battle Drums");
    m.insert("will", "i_Wand of Illusion");
    m.insert("wneg", "i_Wand of Negation");
    m.insert("rdis", "i_Rune of Dispel Magic");
    m.insert("rwat", "i_Rune of the Watcher");
    m.insert("fgrd", "i_Red Drake Egg");
    m.insert("fgrg", "i_Stone Token");
    m.insert("fgdg", "i_Demonic Figurine");
    m.insert("fgfh", "i_Spiked Collar");
    m.insert("fgsk", "i_Book of the Dead");
    m.insert("engs", "i_Enchanted Gemstone");
    m.insert("k3m1", "i_Mooncrystal");
    m.insert("modt", "i_Mask of Death");
    m.insert("sand", "i_Scroll of Animate Dead");
    m.insert("srrc", "i_Scroll of Resurrection");
    m.insert("sror", "i_Scroll of the Beast");
    m.insert("infs", "i_Inferno Stone");
    m.insert("shar", "i_Ice Shard");
    m.insert("wild", "i_Amulet of the Wild");
    m.insert("wswd", "i_Sentry Wards");
    m.insert("whwd", "i_Healing Wards");
    m.insert("wlsd", "i_Wand of Lightning Shield");
    m.insert("wcyc", "i_Wand of the Wind");
    m.insert("rnec", "i_Rod of Necromancy");
    m.insert("pams", "i_Anti-magic Potion");
    m.insert("clfm", "i_Cloak of Flames");
    m.insert("evtl", "i_Talisman of Evasion");
    m.insert("nspi", "i_Necklace of Spell Immunity");
    m.insert("lhst", "i_The Lion Horn of Stormwind");
    m.insert("kpin", "i_Khadgar's Pipe of Insight");
    m.insert("sbch", "i_Scourge Bone Chimes");
    m.insert("afac", "i_Alleria's Flute of Accuracy");
    m.insert("ajen", "i_Ancient Janggo of Endurance");
    m.insert("lgdh", "i_Legion Doom-Horn");
    m.insert("hcun", "i_Hood of Cunning");
    m.insert("mcou", "i_Medallion of Courage");
    m.insert("hval", "i_Helm of Valor");
    m.insert("cnob", "i_Circlet of Nobility");
    m.insert("prvt", "i_Periapt of Vitality");
    m.insert("tgxp", "i_Tome of Greater Experience");
    m.insert("mnst", "i_Mana Stone");
    m.insert("hlst", "i_Health Stone");
    m.insert("tpow", "i_Tome of Knowledge");
    m.insert("tst2", "i_Tome of Strength +2");
    m.insert("tin2", "i_Tome of Intelligence +2");
    m.insert("tdx2", "i_Tome of Agility +2");
    m.insert("rde0", "i_Ring of Protection +1");
    m.insert("rde4", "i_Ring of Protection +5");
    m.insert("rat6", "i_Claws of Attack +6");
    m.insert("rat9", "i_Claws of Attack +9");
    m.insert("ratc", "i_Claws of Attack +12");
    m.insert("ratf", "i_Claws of Attack +15");
    m.insert("manh", "i_Manual of Health");
    m.insert("pmna", "i_Pendant of Mana");
    m.insert("penr", "i_Pendant of Energy");
    m.insert("gcel", "i_Gloves of Haste");
    m.insert("totw", "i_Talisman of the Wild");
    m.insert("phlt", "i_Phat Lewt");
    m.insert("gopr", "i_Glyph of Purification");
    m.insert("ches", "i_Cheese");
    m.insert("mlst", "i_Maul of Strength");
    m.insert("rnsp", "i_Ring of Superiority");
    m.insert("brag", "i_Bracer of Agility");
    m.insert("sksh", "i_Skull Shield");
    m.insert("vddl", "i_Voodoo Doll");
    m.insert("sprn", "i_Spider Ring");
    m.insert("tmmt", "i_Totem of Might");
    m.insert("anfg", "i_Ancient Figurine");
    m.insert("lnrn", "i_Lion's Ring");
    m.insert("iwbr", "i_Ironwood Branch");
    m.insert("jdrn", "i_Jade Ring");
    m.insert("drph", "i_Druid Pouch");
    m.insert("hslv", "i_Healing Salve");
    m.insert("pclr", "i_Clarity Potion");
    m.insert("plcl", "i_Lesser Clarity Potion");
    m.insert("rej1", "i_Minor Replenishment Potion");
    m.insert("rej2", "i_Lesser Replenishment Potion");
    m.insert("rej3", "i_Replenishment Potion");
    m.insert("rej4", "i_Greater Replenishment Potion");
    m.insert("rej5", "i_Lesser Scroll of Replenishment ");
    m.insert("rej6", "i_Greater Scroll of Replenishment ");
    m.insert("sreg", "i_Scroll of Regeneration");
    m.insert("gold", "i_Gold Coins");
    m.insert("lmbr", "i_Bundle of Lumber");
    m.insert("fgun", "i_Flare Gun");
    m.insert("pomn", "i_Potion of Omniscience");
    m.insert("gomn", "i_Glyph of Omniscience");
    m.insert("wneu", "i_Wand of Neutralization");
    m.insert("silk", "i_Spider Silk Broach");
    m.insert("lure", "i_Monster Lure");
    m.insert("skul", "i_Sacrificial Skull");
    m.insert("moon", "i_Moonstone");
    m.insert("brac", "i_Runed Bracers");
    m.insert("vamp", "i_Vampiric Potion");
    m.insert("woms", "i_Wand of Mana Stealing");
    m.insert("tcas", "i_Tiny Castle");
    m.insert("tgrh", "i_Tiny Great Hall");
    m.insert("tsct", "i_Ivory Tower");
    m.insert("wshs", "i_Wand of Shadowsight");
    m.insert("tret", "i_Tome of Retraining");
    m.insert("sneg", "i_Staff of Negation");
    m.insert("stel", "i_Staff of Teleportation");
    m.insert("spre", "i_Staff of Preservation");
    m.insert("mcri", "i_Mechanical Critter");
    m.insert("spsh", "i_Amulet of Spell Shield");
    m.insert("sbok", "i_Spell Book");
    m.insert("ssan", "i_Staff of Sanctuary");
    m.insert("shas", "i_Scroll of Speed");
    m.insert("dust", "i_Dust of Appearance");
    m.insert("oslo", "i_Orb of Slow");
    m.insert("dsum", "i_Diamond of Summoning");
    m.insert("sor1", "i_Shadow Orb +1");
    m.insert("sor2", "i_Shadow Orb +2");
    m.insert("sor3", "i_Shadow Orb +3");
    m.insert("sor4", "i_Shadow Orb +4");
    m.insert("sor5", "i_Shadow Orb +5");
    m.insert("sor6", "i_Shadow Orb +6");
    m.insert("sor7", "i_Shadow Orb +7");
    m.insert("sor8", "i_Shadow Orb +8");
    m.insert("sor9", "i_Shadow Orb +9");
    m.insert("sora", "i_Shadow Orb +10");
    m.insert("sorf", "i_Shadow Orb Fragment");
    m.insert("fwss", "i_Frost Wyrm Skull Shield");
    m.insert("ram1", "i_Ring of the Archmagi");
    m.insert("ram2", "i_Ring of the Archmagi");
    m.insert("ram3", "i_Ring of the Archmagi");
    m.insert("ram4", "i_Ring of the Archmagi");
    m.insert("shtm", "i_Shamanic Totem");
    m.insert("shwd", "i_Shimmerweed");
    m.insert("btst", "i_Battle Standard");
    m.insert("skrt", "i_Skeletal Artifact");
    m.insert("thle", "i_Thunder Lizard Egg");
    m.insert("sclp", "i_Secret Level Powerup");
    m.insert("gldo", "i_Orb of Kil'jaeden");
    m.insert("tbsm", "i_Tiny Blacksmith");
    m.insert("tfar", "i_Tiny Farm");
    m.insert("tlum", "i_Tiny Lumber Mill");
    m.insert("tbar", "i_Tiny Barracks");
    m.insert("tbak", "i_Tiny Altar of Kings");
    m.insert("mgtk", "i_Magic Key Chain");
    m.insert("stre", "i_Staff of Reanimation");
    m.insert("horl", "i_Sacred Relic");
    m.insert("hbth", "i_Helm of Battlethirst");
    m.insert("blba", "i_Bladebane Armor");
    m.insert("rugt", "i_Runed Gauntlets");
    m.insert("frhg", "i_Firehand Gauntlets");
    m.insert("gvsm", "i_Gloves of Spell Mastery");
    m.insert("crdt", "i_Crown of the Deathlord");
    m.insert("arsc", "i_Arcane Scroll");
    m.insert("scul", "i_Scroll of the Unholy Legion");
    m.insert("tmsc", "i_Tome of Sacrifices");
    m.insert("dtsb", "i_Drek'thar's Spellbook");
    m.insert("grsl", "i_Grimoire of Souls");
    m.insert("arsh", "i_Arcanite Shield");
    m.insert("shdt", "i_Shield of the Deathlord");
    m.insert("shhn", "i_Shield of Honor");
    m.insert("shen", "i_Enchanted Shield");
    m.insert("thdm", "i_Thunderlizard Diamond");
    m.insert("stpg", "i_Clockwork Penguin");
    m.insert("shrs", "i_Shimmerglaze Roast");
    m.insert("bfhr", "i_Bloodfeather's Heart");
    m.insert("cosl", "i_Celestial Orb of Souls");
    m.insert("shcw", "i_Shaman Claws");
    m.insert("srbd", "i_Searing Blade");
    m.insert("frgd", "i_Frostguard");
    m.insert("envl", "i_Enchanted Vial");
    m.insert("rump", "i_Rusty Mining Pick");
    m.insert("mort", "i_Mogrin's Report");
    m.insert("srtl", "i_Serathil");
    m.insert("stwa", "i_Sturdy War Axe");
    m.insert("klmm", "i_Killmaim");
    m.insert("rots", "i_Scepter of the Sea");
    m.insert("axas", "i_Ancestral Staff");
    m.insert("mnsf", "i_Mindstaff");
    m.insert("schl", "i_Scepter of Healing");
    m.insert("asbl", "i_Assassin's Blade");
    m.insert("kgal", "i_Keg of Ale");
    m.insert("dphe", "i_Thunder Phoenix Egg");
    m.insert("dkfw", "i_Keg of Thunderwater");
    m.insert("dthb", "i_Thunderbloom Bulb");
    m
});

pub static UNITS: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| {
    let mut m = HashMap::new();
    m.insert("hfoo", "u_Footman");
    m.insert("hkni", "u_Knight");
    m.insert("hmpr", "u_Priest");
    m.insert("hmtm", "u_Mortar Team");
    m.insert("hpea", "u_Peasant");
    m.insert("hrif", "u_Rifleman");
    m.insert("hsor", "u_Sorceress");
    m.insert("hmtt", "u_Siege Engine");
    m.insert("hrtt", "u_Siege Engine");
    m.insert("hgry", "u_Gryphon Rider");
    m.insert("hgyr", "u_Flying Machine");
    m.insert("hspt", "u_Spell Breaker");
    m.insert("hdhw", "u_Dragonhawk Rider");
    m.insert("ebal", "u_Glaive Thrower");
    m.insert("echm", "u_Chimaera");
    m.insert("edoc", "u_Druid of the Claw");
    m.insert("edot", "u_Druid of the Talon");
    m.insert("ewsp", "u_Wisp");
    m.insert("esen", "u_Huntress");
    m.insert("earc", "u_Archer");
    m.insert("edry", "u_Dryad");
    m.insert("ehip", "u_Hippogryph");
    m.insert("emtg", "u_Mountain Giant");
    m.insert("efdr", "u_Faerie Dragon");
    m.insert("ocat", "u_Demolisher");
    m.insert("odoc", "u_Troll Witch Doctor");
    m.insert("ogru", "u_Grunt");
    m.insert("ohun", "u_Troll Headhunter/Berserker");
    m.insert("otbk", "u_Troll Headhunter/Berserker");
    m.insert("okod", "u_Kodo Beast");
    m.insert("opeo", "u_Peon");
    m.insert("orai", "u_Raider");
    m.insert("oshm", "u_Shaman");
    m.insert("otau", "u_Tauren");
    m.insert("owyv", "u_Wind Rider");
    m.insert("ospw", "u_Spirit Walker");
    m.insert("ospm", "u_Spirit Walker");
    m.insert("otbr", "u_Troll Batrider");
    m.insert("uaco", "u_Acolyte");
    m.insert("uabo", "u_Abomination");
    m.insert("uban", "u_Banshee");
    m.insert("ucry", "u_Crypt Fiend");
    m.insert("ufro", "u_Frost Wyrm");
    m.insert("ugar", "u_Gargoyle");
    m.insert("ugho", "u_Ghoul");
    m.insert("unec", "u_Necromancer");
    m.insert("umtw", "u_Meatwagon");
    m.insert("ushd", "u_Shade");
    m.insert("uobs", "u_Obsidian Statue");
    m.insert("ubsp", "u_Destroyer");
    m.insert("nskm", "u_Skeletal Marksman");
    m.insert("nskf", "u_Burning Archer");
    m.insert("nws1", "u_Dragon Hawk");
    m.insert("nban", "u_Bandit");
    m.insert("nrog", "u_Rogue");
    m.insert("nenf", "u_Enforcer");
    m.insert("nass", "u_Assassin");
    m.insert("nbdk", "u_Black Drake");
    m.insert("nrdk", "u_Red Dragon Whelp");
    m.insert("nbdr", "u_Black Dragon Whelp");
    m.insert("nrdr", "u_Red Drake");
    m.insert("nbwm", "u_Black Dragon");
    m.insert("nrwm", "u_Red Dragon");
    m.insert("nadr", "u_Blue Dragon");
    m.insert("nadw", "u_Blue Dragon Whelp");
    m.insert("nadk", "u_Blue Drake");
    m.insert("nbzd", "u_Bronze Dragon");
    m.insert("nbzk", "u_Bronze Drake");
    m.insert("nbzw", "u_Bronze Dragon Whelp");
    m.insert("ngrd", "u_Green Dragon");
    m.insert("ngdk", "u_Green Drake");
    m.insert("ngrw", "u_Green Dragon Whelp");
    m.insert("ncea", "u_Centaur Archer");
    m.insert("ncen", "u_Centaur Outrunner");
    m.insert("ncer", "u_Centaur Drudge");
    m.insert("ndth", "u_Dark Troll High Priest");
    m.insert("ndtp", "u_Dark Troll Shadow Priest");
    m.insert("ndtb", "u_Dark Troll Berserker");
    m.insert("ndtw", "u_Dark Troll Warlord");
    m.insert("ndtr", "u_Dark Troll");
    m.insert("ndtt", "u_Dark Troll Trapper");
    m.insert("nfsh", "u_Forest Troll High Priest");
    m.insert("nfsp", "u_Forest Troll Shadow Priest");
    m.insert("nftr", "u_Forest Troll");
    m.insert("nftb", "u_Forest Troll Berserker");
    m.insert("nftt", "u_Forest Troll Trapper");
    m.insert("nftk", "u_Forest Troll Warlord");
    m.insert("ngrk", "u_Mud Golem");
    m.insert("ngir", "u_Goblin Shredder");
    m.insert("nfrs", "u_Furbolg Shaman");
    m.insert("ngna", "u_Gnoll Poacher");
    m.insert("ngns", "u_Gnoll Assassin");
    m.insert("ngno", "u_Gnoll");
    m.insert("ngnb", "u_Gnoll Brute");
    m.insert("ngnw", "u_Gnoll Warden");
    m.insert("ngnv", "u_Gnoll Overseer");
    m.insert("ngsp", "u_Goblin Sapper");
    m.insert("nhrr", "u_Harpy Rogue");
    m.insert("nhrw", "u_Harpy Windwitch");
    m.insert("nits", "u_Ice Troll Berserker");
    m.insert("nitt", "u_Ice Troll Trapper");
    m.insert("nkob", "u_Kobold");
    m.insert("nkog", "u_Kobold Geomancer");
    m.insert("nthl", "u_Thunder Lizard");
    m.insert("nmfs", "u_Murloc Flesheater");
    m.insert("nmrr", "u_Murloc Huntsman");
    m.insert("nowb", "u_Wildkin");
    m.insert("nrzm", "u_Razormane Medicine Man");
    m.insert("nnwa", "u_Nerubian Warrior");
    m.insert("nnwl", "u_Nerubian Webspinner");
    m.insert("nogr", "u_Ogre Warrior");
    m.insert("nogm", "u_Ogre Mauler");
    m.insert("nogl", "u_Ogre Lord");
    m.insert("nomg", "u_Ogre Magi");
    m.insert("nrvs", "u_Frost Revenant");
    m.insert("nslf", "u_Sludge Flinger");
    m.insert("nsts", "u_Satyr Shadowdancer");
    m.insert("nstl", "u_Satyr Soulstealer");
    m.insert("nzep", "u_Goblin Zeppelin");
    m.insert("ntrt", "u_Giant Sea Turtle");
    m.insert("nlds", "u_Makrura Deepseer");
    m.insert("nlsn", "u_Makrura Snapper");
    m.insert("nmsn", "u_Mur'gul Snarecaster");
    m.insert("nscb", "u_Spider Crab Shorecrawler");
    m.insert("nbot", "u_Transport Ship");
    m.insert("nsc2", "u_Spider Crab Limbripper");
    m.insert("nsc3", "u_Spider Crab Behemoth");
    m.insert("nbdm", "u_Blue Dragonspawn Meddler");
    m.insert("nmgw", "u_Magnataur Warrior");
    m.insert("nanb", "u_Barbed Arachnathid");
    m.insert("nanm", "u_Barbed Arachnathid");
    m.insert("nfps", "u_Polar Furbolg Shaman");
    m.insert("nmgv", "u_Magic Vault");
    m.insert("nitb", "u_Icy Treasure Box");
    m.insert("npfl", "u_Fel Beast");
    m.insert("ndrd", "u_Draenei Darkslayer");
    m.insert("ndrm", "u_Draenei Disciple");
    m.insert("nvdw", "u_Voidwalker");
    m.insert("nvdg", "u_Greater Voidwalker");
    m.insert("nnht", "u_Nether Dragon Hatchling");
    m.insert("nndk", "u_Nether Drake");
    m.insert("nndr", "u_Nether Dragon");
    m
});

pub static BUILDINGS: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| {
    let mut m = HashMap::new();
    m.insert("hhou", "Farm");
    m.insert("halt", "Altar of Kings");
    m.insert("harm", "Workshop");
    m.insert("hars", "Arcane Sanctum");
    m.insert("hbar", "Barracks");
    m.insert("hbla", "Blacksmith");
    m.insert("hgra", "Gryphon Aviary");
    m.insert("hwtw", "Scout Tower");
    m.insert("hvlt", "Arcane Vault");
    m.insert("hlum", "Lumber Mill");
    m.insert("htow", "Town Hall");
    m.insert("hkee", "b_Keep");
    m.insert("hcas", "b_Castle");
    m.insert("hctw", "b_Cannon Tower");
    m.insert("hgtw", "b_Guard Tower");
    m.insert("hatw", "b_Arcane Tower");
    m.insert("etrp", "Ancient Protector");
    m.insert("etol", "Tree of Life");
    m.insert("edob", "Hunter's Hall");
    m.insert("eate", "Altar of Elders");
    m.insert("eden", "Ancient of Wonders");
    m.insert("eaoe", "Ancient of Lore");
    m.insert("eaom", "Ancient of War");
    m.insert("eaow", "Ancient of Wind");
    m.insert("edos", "Chimaera Roost");
    m.insert("emow", "Moon Well");
    m.insert("etoa", "b_Tree of Ages");
    m.insert("etoe", "b_Tree of Eternity");
    m.insert("oalt", "Altar of Storms");
    m.insert("obar", "Barracks");
    m.insert("obea", "Beastiary");
    m.insert("ofor", "War Mill");
    m.insert("ogre", "Great Hall");
    m.insert("osld", "Spirit Lodge");
    m.insert("otrb", "Orc Burrow");
    m.insert("orbr", "Reinforced Orc Burrow");
    m.insert("otto", "Tauren Totem");
    m.insert("ovln", "Voodoo Lounge");
    m.insert("owtw", "Watch Tower");
    m.insert("ofrt", "b_Fortress");
    m.insert("ostr", "b_Stronghold");
    m.insert("uaod", "Altar of Darkness");
    m.insert("unpl", "Necropolis");
    m.insert("usep", "Crypt");
    m.insert("utod", "Temple of the Damned");
    m.insert("utom", "Tomb of Relics");
    m.insert("ugol", "Haunted Gold Mine");
    m.insert("uzig", "Ziggurat");
    m.insert("ubon", "Boneyard");
    m.insert("usap", "Sacrificial Pit");
    m.insert("uslh", "Slaughterhouse");
    m.insert("ugrv", "Graveyard");
    m.insert("unp1", "b_Halls of the Dead");
    m.insert("unp2", "b_Black Citadel");
    m.insert("uzg1", "b_Spirit Tower");
    m.insert("uzg2", "b_Nerubian Tower");
    m
});

pub static UPGRADES: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| {
    let mut m = HashMap::new();
    m.insert("Rhss", "p_Control Magic");
    m.insert("Rhme", "p_Swords");
    m.insert("Rhra", "p_Gunpowder");
    m.insert("Rhar", "p_Plating");
    m.insert("Rhla", "p_Armor");
    m.insert("Rhac", "p_Masonry");
    m.insert("Rhgb", "p_Flying Machine Bombs");
    m.insert("Rhlh", "p_Lumber Harvesting");
    m.insert("Rhde", "p_Defend");
    m.insert("Rhan", "p_Animal War Training");
    m.insert("Rhpt", "p_Priest Training");
    m.insert("Rhst", "p_Sorceress Training");
    m.insert("Rhri", "p_Long Rifles");
    m.insert("Rhse", "p_Magic Sentry");
    m.insert("Rhfl", "p_Flare");
    m.insert("Rhhb", "p_Storm Hammers");
    m.insert("Rhrt", "p_Barrage");
    m.insert("Rhpm", "p_Backpack");
    m.insert("Rhfc", "p_Flak Cannons");
    m.insert("Rhfs", "p_Fragmentation Shards");
    m.insert("Rhcd", "p_Cloud");
    m.insert("Resm", "p_Strength of the Moon");
    m.insert("Resw", "p_Strength of the Wild");
    m.insert("Rema", "p_Moon Armor");
    m.insert("Rerh", "p_Reinforced Hides");
    m.insert("Reuv", "p_Ultravision");
    m.insert("Renb", "p_Nature's Blessing");
    m.insert("Reib", "p_Improved Bows");
    m.insert("Remk", "p_Marksmanship");
    m.insert("Resc", "p_Sentinel");
    m.insert("Remg", "p_Upgrade Moon Glaive");
    m.insert("Redt", "p_Druid of the Talon Training");
    m.insert("Redc", "p_Druid of the Claw Training");
    m.insert("Resi", "p_Abolish Magic");
    m.insert("Reht", "p_Hippogryph Taming");
    m.insert("Recb", "p_Corrosive Breath");
    m.insert("Repb", "p_Vorpal Blades");
    m.insert("Rers", "p_Resistant Skin");
    m.insert("Rehs", "p_Hardened Skin");
    m.insert("Reeb", "p_Mark of the Claw");
    m.insert("Reec", "p_Mark of the Talon");
    m.insert("Rews", "p_Well Spring");
    m.insert("Repm", "p_Backpack");
    m.insert("Roch", "p_Chaos");
    m.insert("Rome", "p_Melee Weapons");
    m.insert("Rora", "p_Ranged Weapons");
    m.insert("Roar", "p_Armor");
    m.insert("Rwdm", "p_War Drums Damage Increase");
    m.insert("Ropg", "p_Pillage");
    m.insert("Robs", "p_Berserker Strength");
    m.insert("Rows", "p_Pulverize");
    m.insert("Roen", "p_Ensnare");
    m.insert("Rovs", "p_Envenomed Spears");
    m.insert("Rowd", "p_Witch Doctor Training");
    m.insert("Rost", "p_Shaman Training");
    m.insert("Rosp", "p_Spiked Barricades");
    m.insert("Rotr", "p_Troll Regeneration");
    m.insert("Rolf", "p_Liquid Fire");
    m.insert("Ropm", "p_Backpack");
    m.insert("Rowt", "p_Spirit Walker Training");
    m.insert("Robk", "p_Berserker Upgrade");
    m.insert("Rorb", "p_Reinforced Defenses");
    m.insert("Robf", "p_Burning Oil");
    m.insert("Rusp", "p_Destroyer Form");
    m.insert("Rume", "p_Unholy Strength");
    m.insert("Rura", "p_Creature Attack");
    m.insert("Ruar", "p_Unholy Armor");
    m.insert("Rucr", "p_Creature Carapace");
    m.insert("Ruac", "p_Cannibalize");
    m.insert("Rugf", "p_Ghoul Frenzy");
    m.insert("Ruwb", "p_Web");
    m.insert("Rusf", "p_Stone Form");
    m.insert("Rune", "p_Necromancer Training");
    m.insert("Ruba", "p_Banshee Training");
    m.insert("Rufb", "p_Freezing Breath");
    m.insert("Rusl", "p_Skeletal Longevity");
    m.insert("Rupc", "p_Disease Cloud");
    m.insert("Rusm", "p_Skeletal Mastery");
    m.insert("Rubu", "p_Burrow");
    m.insert("Ruex", "p_Exhume Corpses");
    m.insert("Rupm", "p_Backpack");
    m
});

pub static ABILITY_TO_HERO: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| {
    let mut m = HashMap::new();
    m.insert("AHbz", "Hamg"); m.insert("AHwe", "Hamg"); m.insert("AHab", "Hamg"); m.insert("AHmt", "Hamg");
    m.insert("AHtb", "Hmkg"); m.insert("AHtc", "Hmkg"); m.insert("AHbh", "Hmkg"); m.insert("AHav", "Hmkg");
    m.insert("AHhb", "Hpal"); m.insert("AHds", "Hpal"); m.insert("AHad", "Hpal"); m.insert("AHre", "Hpal");
    m.insert("AHdr", "Hblm"); m.insert("AHfs", "Hblm"); m.insert("AHbn", "Hblm"); m.insert("AHpx", "Hblm");
    m.insert("AEmb", "Edem"); m.insert("AEim", "Edem"); m.insert("AEev", "Edem"); m.insert("AEme", "Edem");
    m.insert("AEer", "Ekee"); m.insert("AEfn", "Ekee"); m.insert("AEah", "Ekee"); m.insert("AEtq", "Ekee");
    m.insert("AEst", "Emoo"); m.insert("AHfa", "Emoo"); m.insert("AEar", "Emoo"); m.insert("AEsf", "Emoo");
    m.insert("AEbl", "Ewar"); m.insert("AEfk", "Ewar"); m.insert("AEsh", "Ewar"); m.insert("AEsv", "Ewar");
    m.insert("AOwk", "Obla"); m.insert("AOmi", "Obla"); m.insert("AOcr", "Obla"); m.insert("AOww", "Obla");
    m.insert("AOcl", "Ofar"); m.insert("AOfs", "Ofar"); m.insert("AOsf", "Ofar"); m.insert("AOeq", "Ofar");
    m.insert("AOsh", "Otch"); m.insert("AOae", "Otch"); m.insert("AOws", "Otch"); m.insert("AOre", "Otch");
    m.insert("AOhw", "Oshd"); m.insert("AOhx", "Oshd"); m.insert("AOsw", "Oshd"); m.insert("AOvd", "Oshd");
    m.insert("AUdc", "Udea"); m.insert("AUdp", "Udea"); m.insert("AUau", "Udea"); m.insert("AUan", "Udea");
    m.insert("AUcs", "Udre"); m.insert("AUsl", "Udre"); m.insert("AUav", "Udre"); m.insert("AUin", "Udre");
    m.insert("AUfn", "Ulic"); m.insert("AUfa", "Ulic"); m.insert("AUfu", "Ulic"); m.insert("AUdr", "Ulic"); m.insert("AUdd", "Ulic");
    m.insert("AUim", "Ucrl"); m.insert("AUts", "Ucrl"); m.insert("AUcb", "Ucrl"); m.insert("AUls", "Ucrl");
    m.insert("ANbf", "Npbm"); m.insert("ANdb", "Npbm"); m.insert("ANdh", "Npbm"); m.insert("ANef", "Npbm");
    m.insert("ANdr", "Nbrn"); m.insert("ANsi", "Nbrn"); m.insert("ANba", "Nbrn"); m.insert("ANch", "Nbrn");
    m.insert("ANms", "Nngs"); m.insert("ANfa", "Nngs"); m.insert("ANfl", "Nngs"); m.insert("ANto", "Nngs");
    m.insert("ANrf", "Nplh"); m.insert("ANca", "Nplh"); m.insert("ANht", "Nplh"); m.insert("ANdo", "Nplh");
    m.insert("ANsg", "Nbst"); m.insert("ANsq", "Nbst"); m.insert("ANsw", "Nbst"); m.insert("ANst", "Nbst");
    m.insert("ANeg", "Ntin"); m.insert("ANcs", "Ntin"); m.insert("ANc1", "Ntin"); m.insert("ANc2", "Ntin");
    m.insert("ANc3", "Ntin"); m.insert("ANsy", "Ntin"); m.insert("ANs1", "Ntin"); m.insert("ANs2", "Ntin");
    m.insert("ANs3", "Ntin"); m.insert("ANrg", "Ntin"); m.insert("ANg1", "Ntin"); m.insert("ANg2", "Ntin"); m.insert("ANg3", "Ntin");
    m.insert("ANic", "Nfir"); m.insert("ANia", "Nfir"); m.insert("ANso", "Nfir"); m.insert("ANlm", "Nfir"); m.insert("ANvc", "Nfir");
    m.insert("ANhs", "Nalc"); m.insert("ANab", "Nalc"); m.insert("ANcr", "Nalc"); m.insert("ANtm", "Nalc");
    m
});

pub static ULTIMATES: Lazy<std::collections::HashSet<&'static str>> = Lazy::new(|| {
    let mut s = std::collections::HashSet::new();
    s.insert("AEtq"); s.insert("AEme"); s.insert("AEsf"); s.insert("AEsv");
    s.insert("AOww"); s.insert("AOeq"); s.insert("AOre"); s.insert("AOvd");
    s.insert("AUan"); s.insert("AUin"); s.insert("AUdd"); s.insert("AUls");
    s.insert("ANef"); s.insert("ANch"); s.insert("ANto"); s.insert("ANdo");
    s.insert("ANst"); s.insert("ANrg"); s.insert("ANg1"); s.insert("ANg2");
    s.insert("ANg3"); s.insert("ANvc"); s.insert("ANtm");
    s.insert("AHmt"); s.insert("AHav"); s.insert("AHre"); s.insert("AHpx");
    s
});
